from hks_pylib.errors import HKSError


class DoneError(HKSError):
    "Exception is raised by failures in done module."
